/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef, RefObject } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { a } from "@react-spring/three";
import { Mesh, Object3D, Group } from "three";

const Staff = React.memo(function Staff(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/staff-transformed.glb");
  const modelRef: RefObject<Group> = useRef<Group>(null);

  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.007;
    }
  });

  return (
    <group
      {...props}
      dispose={null}
      scale={[3, 3, 3]}
      position={[0, -2, 0]}
      ref={modelRef}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Wizard_Staff3_Wizard_Staff3_0 as Mesh).geometry}
        material={materials.Wizard_Staff3}
        position={[-0.041, 0.983, 0.768]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.04}
      />
      {nodes.Wizard_Staff3_Wizard_Staff3_0_1 && (
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Wizard_Staff3_Wizard_Staff3_0_1 as Mesh).geometry}
          material={materials.Wizard_Staff3}
          position={[-0.041, 0.983, 0.768]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.04}
        />
      )}

      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Wizard_Staff3_Wizard_Staff3_0_2 as Mesh).geometry}
        material={materials.Wizard_Staff3}
        position={[-0.041, 0.983, 0.768]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Wizard_Staff3_Wizard_Staff3_0_3 as Mesh).geometry}
        material={materials.Wizard_Staff3}
        position={[-0.041, 0.983, 0.768]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Wizard_Staff2_Wizard_Staff2_0 as Mesh).geometry}
        material={materials.Wizard_Staff2}
        position={[-0.041, 0.983, 0.768]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.04}
      />
    </group>
  );
});

export default Staff;
useGLTF.preload("/models/staff-transformed.glb");
